### ========================== ###
### === TMUX CONFIGURATION === ###
### ========================== ###

### ====================== ###
### --- initialization --- ###
### ====================== ###

# Change prefix key to C-a, easier to type, same to "screen"
unbind C-b
set -g prefix M-Space

# use vim mode in tmux
setw -g mode-keys vi

# to enable the mouth
set -g mouse off

### ====================== ###
### --- looks and feel --- ###
### ====================== ###
# to enable 256 colors
set -g default-terminal "tmux-256color"
set -as terminal-overrides ',xterm-256color:RGB'

# numbering
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# status bar
set -g status-style bg=default,fg=black,bright
set -g status-left ""
set -g status-right "#[fg=black,bright]#S"

## middle section
set -g window-status-format " #I "
set -g window-status-current-format " #I "
set -g window-status-bell-style "fg=red,nobold"
set -g window-status-current-style "#{?window_zoomed_flag,fg=magenta,bold,fg=magenta,nobold}"

## right section and left section
set -g status-fg green
set -g status-bg black
set -g status-position top
set -g status-justify centre
set -g status-left-length 40
set -g status-left " #S/#W"
set -g status-right "#(~/.tmux/battery.sh)%%"

## clock
set-window-option -g clock-mode-colour colour64 #green

## pane border
set -g pane-border-style fg=green
set -g pane-border-lines simple

### ================ ###
### --- bindings --- ###
### ================ ###

# Reload key
bind r source-file ~/.config/tmux/tmux.conf \; display 'Reloaded!'

# Setting up VIM pane / window managment
unbind '"'
unbind %

bind | split-window -h -c '#{pane_current_path}'
bind - split-window -v -c '#{pane_current_path}'

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind a last-window

# resize panes
bind -r M-h resize-pane -L 5
bind -r M-j resize-pane -D 5
bind -r M-k resize-pane -U 5
bind -r M-l resize-pane -R 5

# to show and hide the satus bar
bind q set-option status

# IF you prefer to use choose-tree instead of fzf
# unbind -T prefix s
# bind   -T prefix s choose-tree -s

# new window in current path 
bind -T prefix c new-window -c "#{pane_current_path}"

### =============== ###
### --- PLUGINS --- ###
### =============== ###

# tmux-plugins
set -g @plugin 'tmux-plugins/tpm'
run '~/.tmux/plugins/tpm/tpm'

# tmux-resurrect plugin
set -g @plugin 'tmux-resurrect'
run '~/.config/tmux/plugins/tmux-resurrect/resurrect.tmux'
set -g @resurrect-save 'C-s'
set -g @resurrect-restore 'R'
set -g @resurrect-dir '~/.config/tmux/resurrect/'

#tmux-yank plugin
run-shell '~/.config/tmux/plugins/tmux-yank/yank.tmux'


set -g @plugin 'vndmp4/tmux-fzf-session-switch'
set -g @fzf-goto-win-width 70
set -g @fzf-goto-win-height 40
set -g @fzf-goto-preview-enabled 'true'
set -g @fzf-goto-session 's'
